/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.9.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QHBoxLayout>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPlainTextEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSlider>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QVBoxLayout>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QWidget *horizontalLayoutWidget;
    QHBoxLayout *ImageView;
    QLabel *IMAGE;
    QPushButton *openPort_Button;
    QComboBox *comboBox;
    QComboBox *comboBox_2;
    QLabel *label;
    QLabel *label_2;
    QLabel *label_3;
    QCheckBox *checkBox;
    QCheckBox *checkBox_2;
    QCheckBox *checkBox_3;
    QLabel *label_4;
    QSlider *horizontalSlider;
    QSlider *horizontalSlider_2;
    QSlider *horizontalSlider_3;
    QSlider *horizontalSlider_4;
    QSlider *horizontalSlider_5;
    QSlider *horizontalSlider_6;
    QLabel *label_6;
    QLabel *label_8;
    QLabel *label_11;
    QLabel *label_9;
    QLabel *label_10;
    QLabel *label_12;
    QLabel *label_13;
    QLabel *label_14;
    QLabel *label_15;
    QLabel *label_16;
    QLabel *label_17;
    QLabel *label_18;
    QLabel *label_7;
    QLabel *label_19;
    QLabel *label_20;
    QLabel *label_21;
    QLabel *label_22;
    QLabel *label_23;
    QLabel *label_24;
    QLabel *label_25;
    QLabel *label_26;
    QLabel *label_27;
    QLabel *label_28;
    QLabel *label_29;
    QSpinBox *spinBox;
    QSpinBox *spinBox_2;
    QSpinBox *spinBox_3;
    QSpinBox *spinBox_4;
    QSpinBox *spinBox_5;
    QSpinBox *spinBox_6;
    QSpinBox *spinBox_7;
    QSpinBox *spinBox_8;
    QSpinBox *spinBox_9;
    QSpinBox *spinBox_10;
    QSpinBox *spinBox_11;
    QSpinBox *spinBox_12;
    QLabel *label_30;
    QLabel *label_31;
    QLabel *label_32;
    QLabel *label_33;
    QLabel *label_34;
    QLabel *label_35;
    QLabel *label_36;
    QLabel *label_37;
    QLabel *label_38;
    QPushButton *pointNUM_Button;
    QLabel *label_39;
    QLabel *label_40;
    QLabel *label_41;
    QLabel *label_42;
    QLabel *label_43;
    QLabel *label_44;
    QLabel *label_45;
    QPushButton *build_Button;
    QPushButton *unbuild_Button;
    QPushButton *point_check_Button;
    QPushButton *point_delete_Button;
    QPushButton *exit_Button;
    QTextEdit *textEdit;
    QTextEdit *textEdit_2;
    QTextEdit *textEdit_3;
    QTextEdit *textEdit_4;
    QTextEdit *textEdit_5;
    QTextEdit *textEdit_6;
    QTextEdit *textEdit_7;
    QPlainTextEdit *plainTextEdit;
    QTextEdit *textEdit_8;
    QCheckBox *checkBox_4;
    QCheckBox *checkBox_5;
    QLabel *label_46;
    QLabel *label_47;
    QPushButton *Help_Button;
    QPushButton *pushButton;
    QWidget *verticalLayoutWidget;
    QVBoxLayout *verticalLayout;
    QPushButton *Start_Button;
    QPushButton *Capture_button;
    QPushButton *End_button;
    QLabel *label_49;
    QLabel *label_50;
    QSpinBox *spinBox_13;
    QLabel *label_48;
    QSpinBox *spinBox_14;
    QLabel *label_51;
    QFrame *line;
    QFrame *line_2;
    QFrame *line_3;
    QFrame *line_4;
    QFrame *line_5;
    QFrame *line_6;
    QFrame *line_7;
    QFrame *line_8;
    QFrame *line_9;
    QFrame *line_10;
    QFrame *line_11;
    QFrame *line_12;
    QFrame *line_13;
    QCheckBox *checkBox_6;
    QLabel *label_5;
    QSpinBox *spinBox_15;
    QMenuBar *menuBar;
    QMenu *menu;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;
    QToolBar *toolBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(1035, 664);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        horizontalLayoutWidget = new QWidget(centralWidget);
        horizontalLayoutWidget->setObjectName(QStringLiteral("horizontalLayoutWidget"));
        horizontalLayoutWidget->setGeometry(QRect(20, 50, 311, 191));
        ImageView = new QHBoxLayout(horizontalLayoutWidget);
        ImageView->setSpacing(6);
        ImageView->setContentsMargins(11, 11, 11, 11);
        ImageView->setObjectName(QStringLiteral("ImageView"));
        ImageView->setContentsMargins(0, 0, 0, 0);
        IMAGE = new QLabel(horizontalLayoutWidget);
        IMAGE->setObjectName(QStringLiteral("IMAGE"));

        ImageView->addWidget(IMAGE);

        openPort_Button = new QPushButton(centralWidget);
        openPort_Button->setObjectName(QStringLiteral("openPort_Button"));
        openPort_Button->setGeometry(QRect(870, 80, 93, 28));
        comboBox = new QComboBox(centralWidget);
        comboBox->setObjectName(QStringLiteral("comboBox"));
        comboBox->setGeometry(QRect(870, 20, 87, 22));
        comboBox_2 = new QComboBox(centralWidget);
        comboBox_2->setObjectName(QStringLiteral("comboBox_2"));
        comboBox_2->setGeometry(QRect(870, 50, 87, 22));
        label = new QLabel(centralWidget);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(830, 20, 41, 16));
        label_2 = new QLabel(centralWidget);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(820, 50, 51, 16));
        label_3 = new QLabel(centralWidget);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(800, 110, 72, 15));
        QFont font;
        font.setBold(true);
        font.setWeight(75);
        label_3->setFont(font);
        checkBox = new QCheckBox(centralWidget);
        checkBox->setObjectName(QStringLiteral("checkBox"));
        checkBox->setGeometry(QRect(870, 110, 151, 19));
        checkBox_2 = new QCheckBox(centralWidget);
        checkBox_2->setObjectName(QStringLiteral("checkBox_2"));
        checkBox_2->setGeometry(QRect(870, 130, 161, 19));
        checkBox_3 = new QCheckBox(centralWidget);
        checkBox_3->setObjectName(QStringLiteral("checkBox_3"));
        checkBox_3->setGeometry(QRect(870, 150, 151, 19));
        label_4 = new QLabel(centralWidget);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(140, 20, 81, 20));
        label_4->setFont(font);
        horizontalSlider = new QSlider(centralWidget);
        horizontalSlider->setObjectName(QStringLiteral("horizontalSlider"));
        horizontalSlider->setGeometry(QRect(400, 90, 61, 22));
        horizontalSlider->setMinimum(500);
        horizontalSlider->setMaximum(2500);
        horizontalSlider->setValue(1500);
        horizontalSlider->setOrientation(Qt::Horizontal);
        horizontalSlider_2 = new QSlider(centralWidget);
        horizontalSlider_2->setObjectName(QStringLiteral("horizontalSlider_2"));
        horizontalSlider_2->setGeometry(QRect(560, 90, 61, 22));
        horizontalSlider_2->setMinimum(500);
        horizontalSlider_2->setMaximum(2500);
        horizontalSlider_2->setValue(1500);
        horizontalSlider_2->setOrientation(Qt::Horizontal);
        horizontalSlider_3 = new QSlider(centralWidget);
        horizontalSlider_3->setObjectName(QStringLiteral("horizontalSlider_3"));
        horizontalSlider_3->setGeometry(QRect(400, 180, 61, 22));
        horizontalSlider_3->setMinimum(500);
        horizontalSlider_3->setMaximum(2500);
        horizontalSlider_3->setValue(1500);
        horizontalSlider_3->setOrientation(Qt::Horizontal);
        horizontalSlider_4 = new QSlider(centralWidget);
        horizontalSlider_4->setObjectName(QStringLiteral("horizontalSlider_4"));
        horizontalSlider_4->setGeometry(QRect(560, 180, 61, 22));
        horizontalSlider_4->setMinimum(500);
        horizontalSlider_4->setMaximum(2500);
        horizontalSlider_4->setValue(1500);
        horizontalSlider_4->setOrientation(Qt::Horizontal);
        horizontalSlider_5 = new QSlider(centralWidget);
        horizontalSlider_5->setObjectName(QStringLiteral("horizontalSlider_5"));
        horizontalSlider_5->setGeometry(QRect(400, 270, 61, 21));
        horizontalSlider_5->setMinimum(500);
        horizontalSlider_5->setMaximum(2500);
        horizontalSlider_5->setValue(1500);
        horizontalSlider_5->setOrientation(Qt::Horizontal);
        horizontalSlider_6 = new QSlider(centralWidget);
        horizontalSlider_6->setObjectName(QStringLiteral("horizontalSlider_6"));
        horizontalSlider_6->setGeometry(QRect(560, 270, 61, 22));
        horizontalSlider_6->setMinimum(500);
        horizontalSlider_6->setMaximum(2500);
        horizontalSlider_6->setValue(1500);
        horizontalSlider_6->setOrientation(Qt::Horizontal);
        label_6 = new QLabel(centralWidget);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(380, 70, 31, 16));
        label_8 = new QLabel(centralWidget);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(380, 160, 31, 16));
        label_11 = new QLabel(centralWidget);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(460, 70, 31, 16));
        label_9 = new QLabel(centralWidget);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(540, 160, 31, 16));
        label_10 = new QLabel(centralWidget);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(540, 250, 31, 16));
        label_12 = new QLabel(centralWidget);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(380, 250, 31, 16));
        label_13 = new QLabel(centralWidget);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(540, 70, 31, 16));
        label_14 = new QLabel(centralWidget);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(460, 160, 31, 16));
        label_15 = new QLabel(centralWidget);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(620, 160, 31, 16));
        label_16 = new QLabel(centralWidget);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(620, 70, 31, 16));
        label_17 = new QLabel(centralWidget);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(460, 250, 31, 16));
        label_18 = new QLabel(centralWidget);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(620, 250, 31, 16));
        label_7 = new QLabel(centralWidget);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(420, 60, 31, 20));
        label_19 = new QLabel(centralWidget);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(420, 140, 31, 20));
        label_20 = new QLabel(centralWidget);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(580, 140, 31, 20));
        label_21 = new QLabel(centralWidget);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(580, 240, 21, 21));
        label_22 = new QLabel(centralWidget);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(420, 240, 31, 20));
        label_23 = new QLabel(centralWidget);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(580, 60, 31, 20));
        label_24 = new QLabel(centralWidget);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(660, 140, 31, 16));
        label_25 = new QLabel(centralWidget);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(660, 240, 31, 16));
        label_26 = new QLabel(centralWidget);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(500, 240, 31, 16));
        label_27 = new QLabel(centralWidget);
        label_27->setObjectName(QStringLiteral("label_27"));
        label_27->setGeometry(QRect(500, 140, 31, 16));
        label_28 = new QLabel(centralWidget);
        label_28->setObjectName(QStringLiteral("label_28"));
        label_28->setGeometry(QRect(660, 60, 31, 16));
        label_29 = new QLabel(centralWidget);
        label_29->setObjectName(QStringLiteral("label_29"));
        label_29->setGeometry(QRect(500, 60, 31, 16));
        spinBox = new QSpinBox(centralWidget);
        spinBox->setObjectName(QStringLiteral("spinBox"));
        spinBox->setGeometry(QRect(410, 110, 51, 22));
        spinBox->setMinimum(500);
        spinBox->setMaximum(2500);
        spinBox->setSingleStep(10);
        spinBox->setValue(1500);
        spinBox_2 = new QSpinBox(centralWidget);
        spinBox_2->setObjectName(QStringLiteral("spinBox_2"));
        spinBox_2->setGeometry(QRect(570, 110, 51, 22));
        spinBox_2->setMinimum(500);
        spinBox_2->setMaximum(2500);
        spinBox_2->setSingleStep(10);
        spinBox_2->setValue(1500);
        spinBox_3 = new QSpinBox(centralWidget);
        spinBox_3->setObjectName(QStringLiteral("spinBox_3"));
        spinBox_3->setGeometry(QRect(410, 200, 51, 22));
        spinBox_3->setMinimum(500);
        spinBox_3->setMaximum(2500);
        spinBox_3->setSingleStep(10);
        spinBox_3->setValue(1500);
        spinBox_4 = new QSpinBox(centralWidget);
        spinBox_4->setObjectName(QStringLiteral("spinBox_4"));
        spinBox_4->setGeometry(QRect(570, 200, 51, 22));
        spinBox_4->setMinimum(500);
        spinBox_4->setMaximum(2500);
        spinBox_4->setSingleStep(10);
        spinBox_4->setValue(1500);
        spinBox_5 = new QSpinBox(centralWidget);
        spinBox_5->setObjectName(QStringLiteral("spinBox_5"));
        spinBox_5->setGeometry(QRect(410, 290, 51, 22));
        spinBox_5->setMinimum(500);
        spinBox_5->setMaximum(2500);
        spinBox_5->setSingleStep(10);
        spinBox_5->setValue(1500);
        spinBox_6 = new QSpinBox(centralWidget);
        spinBox_6->setObjectName(QStringLiteral("spinBox_6"));
        spinBox_6->setGeometry(QRect(570, 290, 51, 22));
        spinBox_6->setMinimum(500);
        spinBox_6->setMaximum(2500);
        spinBox_6->setSingleStep(10);
        spinBox_6->setValue(1500);
        spinBox_7 = new QSpinBox(centralWidget);
        spinBox_7->setObjectName(QStringLiteral("spinBox_7"));
        spinBox_7->setGeometry(QRect(490, 110, 51, 22));
        spinBox_7->setMinimum(100);
        spinBox_7->setMaximum(2000);
        spinBox_7->setSingleStep(10);
        spinBox_7->setValue(1000);
        spinBox_8 = new QSpinBox(centralWidget);
        spinBox_8->setObjectName(QStringLiteral("spinBox_8"));
        spinBox_8->setGeometry(QRect(650, 110, 51, 22));
        spinBox_8->setMinimum(100);
        spinBox_8->setMaximum(2000);
        spinBox_8->setSingleStep(10);
        spinBox_8->setValue(1000);
        spinBox_9 = new QSpinBox(centralWidget);
        spinBox_9->setObjectName(QStringLiteral("spinBox_9"));
        spinBox_9->setGeometry(QRect(490, 200, 51, 22));
        spinBox_9->setMinimum(100);
        spinBox_9->setMaximum(2000);
        spinBox_9->setSingleStep(10);
        spinBox_9->setValue(1000);
        spinBox_10 = new QSpinBox(centralWidget);
        spinBox_10->setObjectName(QStringLiteral("spinBox_10"));
        spinBox_10->setGeometry(QRect(650, 200, 51, 22));
        spinBox_10->setMinimum(100);
        spinBox_10->setMaximum(2000);
        spinBox_10->setSingleStep(10);
        spinBox_10->setValue(1000);
        spinBox_11 = new QSpinBox(centralWidget);
        spinBox_11->setObjectName(QStringLiteral("spinBox_11"));
        spinBox_11->setGeometry(QRect(490, 290, 51, 22));
        spinBox_11->setMinimum(100);
        spinBox_11->setMaximum(2000);
        spinBox_11->setSingleStep(10);
        spinBox_11->setValue(1000);
        spinBox_12 = new QSpinBox(centralWidget);
        spinBox_12->setObjectName(QStringLiteral("spinBox_12"));
        spinBox_12->setGeometry(QRect(650, 290, 51, 22));
        spinBox_12->setMinimum(100);
        spinBox_12->setMaximum(2000);
        spinBox_12->setSingleStep(10);
        spinBox_12->setValue(1000);
        label_30 = new QLabel(centralWidget);
        label_30->setObjectName(QStringLiteral("label_30"));
        label_30->setGeometry(QRect(380, 50, 31, 16));
        label_31 = new QLabel(centralWidget);
        label_31->setObjectName(QStringLiteral("label_31"));
        label_31->setGeometry(QRect(540, 230, 31, 16));
        label_32 = new QLabel(centralWidget);
        label_32->setObjectName(QStringLiteral("label_32"));
        label_32->setGeometry(QRect(380, 230, 31, 16));
        label_33 = new QLabel(centralWidget);
        label_33->setObjectName(QStringLiteral("label_33"));
        label_33->setGeometry(QRect(540, 130, 31, 16));
        label_34 = new QLabel(centralWidget);
        label_34->setObjectName(QStringLiteral("label_34"));
        label_34->setGeometry(QRect(380, 130, 31, 16));
        label_35 = new QLabel(centralWidget);
        label_35->setObjectName(QStringLiteral("label_35"));
        label_35->setGeometry(QRect(540, 50, 31, 16));
        label_36 = new QLabel(centralWidget);
        label_36->setObjectName(QStringLiteral("label_36"));
        label_36->setGeometry(QRect(490, 10, 131, 31));
        label_36->setFont(font);
        label_36->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_37 = new QLabel(centralWidget);
        label_37->setObjectName(QStringLiteral("label_37"));
        label_37->setGeometry(QRect(840, 185, 111, 21));
        label_37->setFont(font);
        label_38 = new QLabel(centralWidget);
        label_38->setObjectName(QStringLiteral("label_38"));
        label_38->setGeometry(QRect(760, 290, 121, 16));
        pointNUM_Button = new QPushButton(centralWidget);
        pointNUM_Button->setObjectName(QStringLiteral("pointNUM_Button"));
        pointNUM_Button->setGeometry(QRect(940, 280, 71, 28));
        QFont font1;
        font1.setPointSize(7);
        pointNUM_Button->setFont(font1);
        label_39 = new QLabel(centralWidget);
        label_39->setObjectName(QStringLiteral("label_39"));
        label_39->setGeometry(QRect(820, 330, 72, 15));
        label_40 = new QLabel(centralWidget);
        label_40->setObjectName(QStringLiteral("label_40"));
        label_40->setGeometry(QRect(930, 330, 41, 16));
        label_41 = new QLabel(centralWidget);
        label_41->setObjectName(QStringLiteral("label_41"));
        label_41->setGeometry(QRect(820, 370, 21, 16));
        QFont font2;
        font2.setPointSize(12);
        label_41->setFont(font2);
        label_42 = new QLabel(centralWidget);
        label_42->setObjectName(QStringLiteral("label_42"));
        label_42->setGeometry(QRect(820, 410, 21, 16));
        label_42->setFont(font2);
        label_43 = new QLabel(centralWidget);
        label_43->setObjectName(QStringLiteral("label_43"));
        label_43->setGeometry(QRect(820, 450, 21, 16));
        label_43->setFont(font2);
        label_44 = new QLabel(centralWidget);
        label_44->setObjectName(QStringLiteral("label_44"));
        label_44->setGeometry(QRect(800, 490, 31, 16));
        label_44->setFont(font2);
        label_45 = new QLabel(centralWidget);
        label_45->setObjectName(QStringLiteral("label_45"));
        label_45->setGeometry(QRect(800, 530, 31, 16));
        label_45->setFont(font2);
        build_Button = new QPushButton(centralWidget);
        build_Button->setObjectName(QStringLiteral("build_Button"));
        build_Button->setGeometry(QRect(930, 480, 93, 28));
        unbuild_Button = new QPushButton(centralWidget);
        unbuild_Button->setObjectName(QStringLiteral("unbuild_Button"));
        unbuild_Button->setGeometry(QRect(930, 520, 93, 28));
        point_check_Button = new QPushButton(centralWidget);
        point_check_Button->setObjectName(QStringLiteral("point_check_Button"));
        point_check_Button->setGeometry(QRect(930, 360, 93, 28));
        point_delete_Button = new QPushButton(centralWidget);
        point_delete_Button->setObjectName(QStringLiteral("point_delete_Button"));
        point_delete_Button->setGeometry(QRect(930, 400, 93, 28));
        exit_Button = new QPushButton(centralWidget);
        exit_Button->setObjectName(QStringLiteral("exit_Button"));
        exit_Button->setGeometry(QRect(910, 560, 93, 28));
        textEdit = new QTextEdit(centralWidget);
        textEdit->setObjectName(QStringLiteral("textEdit"));
        textEdit->setGeometry(QRect(880, 280, 41, 31));
        textEdit_2 = new QTextEdit(centralWidget);
        textEdit_2->setObjectName(QStringLiteral("textEdit_2"));
        textEdit_2->setGeometry(QRect(880, 320, 41, 31));
        textEdit_3 = new QTextEdit(centralWidget);
        textEdit_3->setObjectName(QStringLiteral("textEdit_3"));
        textEdit_3->setGeometry(QRect(850, 360, 71, 31));
        textEdit_4 = new QTextEdit(centralWidget);
        textEdit_4->setObjectName(QStringLiteral("textEdit_4"));
        textEdit_4->setGeometry(QRect(850, 400, 71, 31));
        textEdit_5 = new QTextEdit(centralWidget);
        textEdit_5->setObjectName(QStringLiteral("textEdit_5"));
        textEdit_5->setGeometry(QRect(850, 440, 71, 31));
        textEdit_6 = new QTextEdit(centralWidget);
        textEdit_6->setObjectName(QStringLiteral("textEdit_6"));
        textEdit_6->setGeometry(QRect(850, 480, 71, 31));
        textEdit_7 = new QTextEdit(centralWidget);
        textEdit_7->setObjectName(QStringLiteral("textEdit_7"));
        textEdit_7->setGeometry(QRect(850, 520, 71, 31));
        plainTextEdit = new QPlainTextEdit(centralWidget);
        plainTextEdit->setObjectName(QStringLiteral("plainTextEdit"));
        plainTextEdit->setGeometry(QRect(390, 470, 331, 111));
        textEdit_8 = new QTextEdit(centralWidget);
        textEdit_8->setObjectName(QStringLiteral("textEdit_8"));
        textEdit_8->setGeometry(QRect(390, 370, 331, 61));
        checkBox_4 = new QCheckBox(centralWidget);
        checkBox_4->setObjectName(QStringLiteral("checkBox_4"));
        checkBox_4->setGeometry(QRect(40, 260, 121, 19));
        checkBox_5 = new QCheckBox(centralWidget);
        checkBox_5->setObjectName(QStringLiteral("checkBox_5"));
        checkBox_5->setGeometry(QRect(190, 260, 111, 19));
        label_46 = new QLabel(centralWidget);
        label_46->setObjectName(QStringLiteral("label_46"));
        label_46->setGeometry(QRect(380, 350, 61, 16));
        label_46->setFont(font);
        label_47 = new QLabel(centralWidget);
        label_47->setObjectName(QStringLiteral("label_47"));
        label_47->setGeometry(QRect(380, 440, 51, 16));
        label_47->setFont(font);
        Help_Button = new QPushButton(centralWidget);
        Help_Button->setObjectName(QStringLiteral("Help_Button"));
        Help_Button->setGeometry(QRect(800, 560, 93, 28));
        pushButton = new QPushButton(centralWidget);
        pushButton->setObjectName(QStringLiteral("pushButton"));
        pushButton->setGeometry(QRect(970, 80, 51, 28));
        verticalLayoutWidget = new QWidget(centralWidget);
        verticalLayoutWidget->setObjectName(QStringLiteral("verticalLayoutWidget"));
        verticalLayoutWidget->setGeometry(QRect(70, 370, 201, 121));
        verticalLayout = new QVBoxLayout(verticalLayoutWidget);
        verticalLayout->setSpacing(6);
        verticalLayout->setContentsMargins(11, 11, 11, 11);
        verticalLayout->setObjectName(QStringLiteral("verticalLayout"));
        verticalLayout->setContentsMargins(0, 0, 0, 0);
        Start_Button = new QPushButton(verticalLayoutWidget);
        Start_Button->setObjectName(QStringLiteral("Start_Button"));

        verticalLayout->addWidget(Start_Button);

        Capture_button = new QPushButton(verticalLayoutWidget);
        Capture_button->setObjectName(QStringLiteral("Capture_button"));

        verticalLayout->addWidget(Capture_button);

        End_button = new QPushButton(verticalLayoutWidget);
        End_button->setObjectName(QStringLiteral("End_button"));

        verticalLayout->addWidget(End_button);

        label_49 = new QLabel(centralWidget);
        label_49->setObjectName(QStringLiteral("label_49"));
        label_49->setGeometry(QRect(830, 240, 121, 21));
        label_50 = new QLabel(centralWidget);
        label_50->setObjectName(QStringLiteral("label_50"));
        label_50->setGeometry(QRect(830, 260, 121, 16));
        spinBox_13 = new QSpinBox(centralWidget);
        spinBox_13->setObjectName(QStringLiteral("spinBox_13"));
        spinBox_13->setGeometry(QRect(940, 250, 51, 22));
        spinBox_13->setMinimum(20);
        spinBox_13->setMaximum(2000);
        spinBox_13->setSingleStep(10);
        spinBox_13->setValue(100);
        label_48 = new QLabel(centralWidget);
        label_48->setObjectName(QStringLiteral("label_48"));
        label_48->setGeometry(QRect(1000, 250, 21, 16));
        spinBox_14 = new QSpinBox(centralWidget);
        spinBox_14->setObjectName(QStringLiteral("spinBox_14"));
        spinBox_14->setGeometry(QRect(940, 210, 51, 22));
        spinBox_14->setMinimum(0);
        spinBox_14->setMaximum(200);
        spinBox_14->setSingleStep(5);
        spinBox_14->setValue(50);
        label_51 = new QLabel(centralWidget);
        label_51->setObjectName(QStringLiteral("label_51"));
        label_51->setGeometry(QRect(830, 210, 111, 20));
        line = new QFrame(centralWidget);
        line->setObjectName(QStringLiteral("line"));
        line->setGeometry(QRect(320, 0, 51, 621));
        QFont font3;
        font3.setBold(false);
        font3.setWeight(50);
        line->setFont(font3);
        line->setFrameShape(QFrame::VLine);
        line->setFrameShadow(QFrame::Sunken);
        line_2 = new QFrame(centralWidget);
        line_2->setObjectName(QStringLiteral("line_2"));
        line_2->setGeometry(QRect(350, 330, 391, 20));
        line_2->setFrameShape(QFrame::HLine);
        line_2->setFrameShadow(QFrame::Sunken);
        line_3 = new QFrame(centralWidget);
        line_3->setObjectName(QStringLiteral("line_3"));
        line_3->setGeometry(QRect(740, 0, 20, 621));
        line_3->setFrameShape(QFrame::VLine);
        line_3->setFrameShadow(QFrame::Sunken);
        line_4 = new QFrame(centralWidget);
        line_4->setObjectName(QStringLiteral("line_4"));
        line_4->setGeometry(QRect(750, 550, 281, 16));
        line_4->setFrameShape(QFrame::HLine);
        line_4->setFrameShadow(QFrame::Sunken);
        line_5 = new QFrame(centralWidget);
        line_5->setObjectName(QStringLiteral("line_5"));
        line_5->setGeometry(QRect(750, 170, 281, 16));
        line_5->setFrameShape(QFrame::HLine);
        line_5->setFrameShadow(QFrame::Sunken);
        line_6 = new QFrame(centralWidget);
        line_6->setObjectName(QStringLiteral("line_6"));
        line_6->setGeometry(QRect(10, 35, 331, 16));
        line_6->setFrameShape(QFrame::HLine);
        line_6->setFrameShadow(QFrame::Sunken);
        line_7 = new QFrame(centralWidget);
        line_7->setObjectName(QStringLiteral("line_7"));
        line_7->setGeometry(QRect(10, 242, 331, 16));
        line_7->setFrameShape(QFrame::HLine);
        line_7->setFrameShadow(QFrame::Sunken);
        line_8 = new QFrame(centralWidget);
        line_8->setObjectName(QStringLiteral("line_8"));
        line_8->setGeometry(QRect(5, 41, 16, 210));
        line_8->setFrameShape(QFrame::VLine);
        line_8->setFrameShadow(QFrame::Sunken);
        line_9 = new QFrame(centralWidget);
        line_9->setObjectName(QStringLiteral("line_9"));
        line_9->setGeometry(QRect(330, 40, 20, 210));
        line_9->setFrameShape(QFrame::VLine);
        line_9->setFrameShadow(QFrame::Sunken);
        line_10 = new QFrame(centralWidget);
        line_10->setObjectName(QStringLiteral("line_10"));
        line_10->setGeometry(QRect(60, 355, 221, 16));
        line_10->setFrameShape(QFrame::HLine);
        line_10->setFrameShadow(QFrame::Sunken);
        line_11 = new QFrame(centralWidget);
        line_11->setObjectName(QStringLiteral("line_11"));
        line_11->setGeometry(QRect(60, 493, 221, 20));
        line_11->setFrameShape(QFrame::HLine);
        line_11->setFrameShadow(QFrame::Sunken);
        line_12 = new QFrame(centralWidget);
        line_12->setObjectName(QStringLiteral("line_12"));
        line_12->setGeometry(QRect(50, 360, 21, 141));
        line_12->setFrameShape(QFrame::VLine);
        line_12->setFrameShadow(QFrame::Sunken);
        line_13 = new QFrame(centralWidget);
        line_13->setObjectName(QStringLiteral("line_13"));
        line_13->setGeometry(QRect(270, 360, 20, 141));
        line_13->setFrameShape(QFrame::VLine);
        line_13->setFrameShadow(QFrame::Sunken);
        checkBox_6 = new QCheckBox(centralWidget);
        checkBox_6->setObjectName(QStringLiteral("checkBox_6"));
        checkBox_6->setGeometry(QRect(40, 300, 91, 19));
        label_5 = new QLabel(centralWidget);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(180, 300, 72, 15));
        spinBox_15 = new QSpinBox(centralWidget);
        spinBox_15->setObjectName(QStringLiteral("spinBox_15"));
        spinBox_15->setGeometry(QRect(250, 295, 46, 22));
        spinBox_15->setMaximum(5);
        MainWindow->setCentralWidget(centralWidget);
        horizontalLayoutWidget->raise();
        openPort_Button->raise();
        comboBox->raise();
        comboBox_2->raise();
        label->raise();
        label_2->raise();
        label_3->raise();
        checkBox->raise();
        checkBox_2->raise();
        checkBox_3->raise();
        label_4->raise();
        horizontalSlider->raise();
        horizontalSlider_2->raise();
        horizontalSlider_3->raise();
        horizontalSlider_4->raise();
        horizontalSlider_5->raise();
        horizontalSlider_6->raise();
        label_6->raise();
        label_8->raise();
        label_11->raise();
        label_9->raise();
        label_10->raise();
        label_12->raise();
        label_13->raise();
        label_14->raise();
        label_15->raise();
        label_16->raise();
        label_17->raise();
        label_18->raise();
        label_7->raise();
        label_19->raise();
        label_20->raise();
        label_21->raise();
        label_22->raise();
        label_23->raise();
        label_24->raise();
        label_25->raise();
        label_26->raise();
        label_27->raise();
        label_28->raise();
        label_29->raise();
        spinBox->raise();
        spinBox_2->raise();
        spinBox_3->raise();
        spinBox_4->raise();
        spinBox_5->raise();
        spinBox_6->raise();
        spinBox_7->raise();
        spinBox_8->raise();
        spinBox_9->raise();
        spinBox_10->raise();
        spinBox_11->raise();
        spinBox_12->raise();
        label_30->raise();
        label_31->raise();
        label_32->raise();
        label_33->raise();
        label_34->raise();
        label_35->raise();
        label_36->raise();
        label_37->raise();
        label_38->raise();
        pointNUM_Button->raise();
        label_39->raise();
        label_40->raise();
        label_41->raise();
        label_42->raise();
        label_43->raise();
        label_44->raise();
        label_45->raise();
        build_Button->raise();
        unbuild_Button->raise();
        point_check_Button->raise();
        point_delete_Button->raise();
        exit_Button->raise();
        textEdit->raise();
        textEdit_2->raise();
        textEdit_3->raise();
        textEdit_4->raise();
        textEdit_5->raise();
        textEdit_6->raise();
        textEdit_7->raise();
        plainTextEdit->raise();
        checkBox_4->raise();
        checkBox_5->raise();
        textEdit_8->raise();
        label_46->raise();
        label_47->raise();
        Help_Button->raise();
        pushButton->raise();
        verticalLayoutWidget->raise();
        label_49->raise();
        label_50->raise();
        spinBox_13->raise();
        label_48->raise();
        spinBox_14->raise();
        label_51->raise();
        line->raise();
        line_2->raise();
        line_3->raise();
        line_4->raise();
        line_5->raise();
        line_6->raise();
        line_7->raise();
        line_8->raise();
        line_9->raise();
        line_10->raise();
        line_11->raise();
        line_12->raise();
        line_13->raise();
        checkBox_6->raise();
        label_5->raise();
        spinBox_15->raise();
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 1035, 26));
        menu = new QMenu(menuBar);
        menu->setObjectName(QStringLiteral("menu"));
        MainWindow->setMenuBar(menuBar);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QStringLiteral("mainToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        MainWindow->setStatusBar(statusBar);
        toolBar = new QToolBar(MainWindow);
        toolBar->setObjectName(QStringLiteral("toolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, toolBar);

        menuBar->addAction(menu->menuAction());

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", Q_NULLPTR));
        IMAGE->setText(QString());
        openPort_Button->setText(QApplication::translate("MainWindow", "\346\211\223\345\274\200\344\270\262\345\217\243", Q_NULLPTR));
        comboBox_2->clear();
        comboBox_2->insertItems(0, QStringList()
         << QApplication::translate("MainWindow", "9600", Q_NULLPTR)
         << QApplication::translate("MainWindow", "38400", Q_NULLPTR)
         << QApplication::translate("MainWindow", "115200", Q_NULLPTR)
        );
        label->setText(QApplication::translate("MainWindow", "\344\270\262\345\217\243", Q_NULLPTR));
        label_2->setText(QApplication::translate("MainWindow", "\346\263\242\347\211\271\347\216\207", Q_NULLPTR));
        label_3->setText(QApplication::translate("MainWindow", "\346\250\241\345\274\217\351\200\211\346\213\251", Q_NULLPTR));
        checkBox->setText(QApplication::translate("MainWindow", "\346\273\221\346\235\241\347\213\254\347\253\213\346\216\247\345\210\266\346\250\241\345\274\217", Q_NULLPTR));
        checkBox_2->setText(QApplication::translate("MainWindow", "\347\254\233\345\215\241\345\260\224\347\251\272\351\227\264\350\247\204\345\210\222\346\250\241\345\274\217", Q_NULLPTR));
        checkBox_3->setText(QApplication::translate("MainWindow", "\345\205\263\350\212\202\347\251\272\351\227\264\350\247\204\345\210\222\346\250\241\345\274\217", Q_NULLPTR));
        label_4->setText(QApplication::translate("MainWindow", "\350\247\206\350\247\211\346\230\276\347\244\272\345\214\272", Q_NULLPTR));
        label_6->setText(QApplication::translate("MainWindow", "500", Q_NULLPTR));
        label_8->setText(QApplication::translate("MainWindow", "500", Q_NULLPTR));
        label_11->setText(QApplication::translate("MainWindow", "2500", Q_NULLPTR));
        label_9->setText(QApplication::translate("MainWindow", "500", Q_NULLPTR));
        label_10->setText(QApplication::translate("MainWindow", "500", Q_NULLPTR));
        label_12->setText(QApplication::translate("MainWindow", "500", Q_NULLPTR));
        label_13->setText(QApplication::translate("MainWindow", "500", Q_NULLPTR));
        label_14->setText(QApplication::translate("MainWindow", "2500", Q_NULLPTR));
        label_15->setText(QApplication::translate("MainWindow", "2500", Q_NULLPTR));
        label_16->setText(QApplication::translate("MainWindow", "2500", Q_NULLPTR));
        label_17->setText(QApplication::translate("MainWindow", "2500", Q_NULLPTR));
        label_18->setText(QApplication::translate("MainWindow", "2500", Q_NULLPTR));
        label_7->setText(QApplication::translate("MainWindow", "PWM", Q_NULLPTR));
        label_19->setText(QApplication::translate("MainWindow", "PWM", Q_NULLPTR));
        label_20->setText(QApplication::translate("MainWindow", "PWM", Q_NULLPTR));
        label_21->setText(QApplication::translate("MainWindow", "PWM", Q_NULLPTR));
        label_22->setText(QApplication::translate("MainWindow", "PWM", Q_NULLPTR));
        label_23->setText(QApplication::translate("MainWindow", "PWM", Q_NULLPTR));
        label_24->setText(QApplication::translate("MainWindow", "TIME", Q_NULLPTR));
        label_25->setText(QApplication::translate("MainWindow", "TIME", Q_NULLPTR));
        label_26->setText(QApplication::translate("MainWindow", "TIME", Q_NULLPTR));
        label_27->setText(QApplication::translate("MainWindow", "TIME", Q_NULLPTR));
        label_28->setText(QApplication::translate("MainWindow", "TIME", Q_NULLPTR));
        label_29->setText(QApplication::translate("MainWindow", "TIME", Q_NULLPTR));
        label_30->setText(QApplication::translate("MainWindow", "\316\2700", Q_NULLPTR));
        label_31->setText(QApplication::translate("MainWindow", "\316\2705", Q_NULLPTR));
        label_32->setText(QApplication::translate("MainWindow", "\316\2704", Q_NULLPTR));
        label_33->setText(QApplication::translate("MainWindow", "\316\2703", Q_NULLPTR));
        label_34->setText(QApplication::translate("MainWindow", "\316\2702", Q_NULLPTR));
        label_35->setText(QApplication::translate("MainWindow", "\316\2701", Q_NULLPTR));
        label_36->setText(QApplication::translate("MainWindow", "\346\273\221\346\235\241\347\213\254\347\253\213\346\216\247\345\210\266\346\250\241\345\274\217", Q_NULLPTR));
        label_37->setText(QApplication::translate("MainWindow", "\350\275\250\350\277\271\350\247\204\345\210\222\346\250\241\345\274\217", Q_NULLPTR));
        label_38->setText(QApplication::translate("MainWindow", "\350\256\276\347\275\256\350\247\204\345\210\222\347\202\271\344\270\252\346\225\260\357\274\232", Q_NULLPTR));
        pointNUM_Button->setText(QApplication::translate("MainWindow", "\347\241\256\350\256\244", Q_NULLPTR));
        label_39->setText(QApplication::translate("MainWindow", "\350\257\267\350\276\223\345\205\245\347\254\254", Q_NULLPTR));
        label_40->setText(QApplication::translate("MainWindow", "\344\270\252\347\202\271\357\274\232", Q_NULLPTR));
        label_41->setText(QApplication::translate("MainWindow", "X", Q_NULLPTR));
        label_42->setText(QApplication::translate("MainWindow", "Y", Q_NULLPTR));
        label_43->setText(QApplication::translate("MainWindow", "Z", Q_NULLPTR));
        label_44->setText(QApplication::translate("MainWindow", "\316\2704", Q_NULLPTR));
        label_45->setText(QApplication::translate("MainWindow", "\316\2705", Q_NULLPTR));
        build_Button->setText(QApplication::translate("MainWindow", "\347\241\256\350\256\244\350\247\204\345\210\222", Q_NULLPTR));
        unbuild_Button->setText(QApplication::translate("MainWindow", "\345\217\226\346\266\210\350\247\204\345\210\222", Q_NULLPTR));
        point_check_Button->setText(QApplication::translate("MainWindow", "\347\241\256\350\256\244\346\255\244\347\202\271", Q_NULLPTR));
        point_delete_Button->setText(QApplication::translate("MainWindow", "\345\217\226\346\266\210\344\270\212\347\202\271", Q_NULLPTR));
        exit_Button->setText(QApplication::translate("MainWindow", "\351\200\200\345\207\272", Q_NULLPTR));
#ifndef QT_NO_TOOLTIP
        plainTextEdit->setToolTip(QApplication::translate("MainWindow", "<html><head/><body><p>\350\276\223\345\207\272\346\241\206</p></body></html>", Q_NULLPTR));
#endif // QT_NO_TOOLTIP
        checkBox_4->setText(QApplication::translate("MainWindow", "eye-to-hand", Q_NULLPTR));
        checkBox_5->setText(QApplication::translate("MainWindow", "eye-in-hand", Q_NULLPTR));
        label_46->setText(QApplication::translate("MainWindow", "\344\274\240\350\276\223\346\217\220\347\244\272", Q_NULLPTR));
        label_47->setText(QApplication::translate("MainWindow", "\350\276\223\345\207\272\346\241\206", Q_NULLPTR));
        Help_Button->setText(QApplication::translate("MainWindow", "\345\270\256\345\212\251", Q_NULLPTR));
        pushButton->setText(QApplication::translate("MainWindow", "\345\244\215\344\275\215", Q_NULLPTR));
        Start_Button->setText(QApplication::translate("MainWindow", "\345\274\200\345\247\213", Q_NULLPTR));
        Capture_button->setText(QApplication::translate("MainWindow", "\350\267\237\350\270\252\345\244\215\344\275\215", Q_NULLPTR));
        End_button->setText(QApplication::translate("MainWindow", "\345\217\226\346\266\210\350\267\237\350\270\252", Q_NULLPTR));
        label_49->setText(QApplication::translate("MainWindow", "\347\254\233\345\215\241\345\260\224\347\251\272\351\227\264\346\250\241\345\274\217", Q_NULLPTR));
        label_50->setText(QApplication::translate("MainWindow", "\345\217\257\350\256\276\347\275\256\345\223\215\345\272\224\346\227\266\351\227\264", Q_NULLPTR));
        label_48->setText(QApplication::translate("MainWindow", "ms", Q_NULLPTR));
        label_51->setText(QApplication::translate("MainWindow", "\347\254\233\345\215\241\345\260\224\347\262\276\345\272\246\350\256\276\347\275\256", Q_NULLPTR));
        checkBox_6->setText(QApplication::translate("MainWindow", "\347\233\256\346\240\207\350\267\237\350\270\252", Q_NULLPTR));
        label_5->setText(QApplication::translate("MainWindow", "\345\247\277\346\200\201\351\200\211\346\213\251\357\274\232", Q_NULLPTR));
        menu->setTitle(QApplication::translate("MainWindow", "\346\234\272\346\242\260\350\207\202\344\270\212\344\275\215\346\234\272", Q_NULLPTR));
        toolBar->setWindowTitle(QApplication::translate("MainWindow", "toolBar", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
